spring.profiles.active=prod
spring.application.name=condominio

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.api-docs.path=/v3/api-docs

springdoc.swagger-ui.operationsSorter=method
api.security.token.secret=${JWT_SECRET:12345678}